### PR TITLE
plane visu

### PR DESCRIPTION
**Pull request by mlelarge**
First example, taken from: https://youtu.be/aUkBa1zMKv4
There is perhaps a bettre representation of the particles with their weights?

### CODE REVIEW

**Comment by gbdrt** [comment]
Added support for a ScalarLinearTracker to track 1D Normal distribution.
The 1D version of the plane visu is in `visu/plane_1d.jl`.

**Comment by mlelarge** [comment]
Added `visu/plane_1d_linear.jl` working in symbolic. Need to check the variance seems to be different from previous anim, TBC.

**Comment by mlelarge** [comment]
There is still a pb with the scalar version. Code is running but results are probably not correct?
I corrected previous non-scalar version where variables with a name Stdev where indead used as variances...

**Comment by wazizian** [comment]
(I'm on it)

**Comment by mlelarge** [comment]
I think this is a pb with resampling for the scalar version.

**Comment by mlelarge** [comment]
I did a little bit of refactoring for the various cases.
I added a new case where the plane has a varying speed. The corresponding model has a linear part and a non-linear one. Symbolic calculation is done right. Need to check if variance is lower (on such a short example, it might be hard to see?).

**Pull request merged**
